language: python
python:
  - '2.7'
services:
  - elasticsearch
install:
  - travis_retry pip install -e .
  - travis_retry pip install file://$(pwd)#egg=betty-cropper[dev]
script:
  - py.test tests/
sudo: false